apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: backstage-systems
  title: Gitops filebeat
  description: This template will create filebeat in Backstage
  tags:
    - filebeat
spec:
  owner: filebeat
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide Needed Information
      required:
        - OCP_LOGSTASH_SERVER
        - OCP_CLUSTER_NAME
        - OCP_CLUSTER_URL
      properties:
        OCP_LOGSTASH_SERVER:
          title: OCP_LOGSTASH_SERVER
          type: string
          description: Enter your OCP_LOGSTASH_SERVER
          
        OCP_CLUSTER_NAME:
          title: OCP_CLUSTER_NAME
          type: string
          description: Enter your OCP_CLUSTER_NAME
          
        OCP_CLUSTER_URL:
          title: OCP_CLUSTER_URL
          type: string
          description: Enter your OCP_CLUSTER_URL
 
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'OCP_LOGSTASH_SERVER name you entered:, ${{ parameters.OCP_LOGSTASH_SERVER }}!'

    - id: trigger-workflow
      name: trigger workflow
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=demo&owner=venkatram8500'
        workflowId: branch.yml
        branchOrTagName: main
        token: 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
        
          
        
         
