apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: backstage-systems
  title: Gitops filebeat
  description: This template will create filebeat in Backstage
  tags:
    - filebeat

spec:
  owner: user:VMADHIRI@volvocars.com
  type: service
  parameters:
    - title: Provide Needed Information
      required:
        - OCP_LOGSTASH_SERVER

      properties:
        OCP_LOGSTASH_SERVER:
          title: OCP_LOGSTASH_SERVER
          type: string
          description: Select OCP_LOGSTASH_SERVER
          default: none
          enum:
            - Dev_ocpplatform.logstash-logs.volvocars.net:5045
            - Prod_ocpplatform.logstash-logs.volvocars.net:5045
            - Test_ocpplatform.logstash-logs.volvocars.net:5045

      
      dependencies:
        OCP_LOGSTASH_SERVER:
          oneOf:
            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Dev_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME1:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: test-net
                OCP_CLUSTER_URL1:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: my cluster

            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Prod_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME2:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: try-net
                OCP_CLUSTER_URL2:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: our cluster


            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Test_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME3:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: try-net
                OCP_CLUSTER_URL3:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: our cluster


  steps:
    - id: for dev
      name: Create Contact Point dev
      if: ${{ parameters.OCP_LOGSTASH_SERVER === "Dev_ocpplatform.logstash-logs.volvocars.net:5045" }}
      action: debug:log
      input:
        message: 'selected Dev_ocpplatform.logstash-logs.volvocars.net:5045'
      

    - id: for prod
      name: Create Contact Point prod
      if: ${{ parameters.OCP_LOGSTASH_SERVER === "Prod_ocpplatform.logstash-logs.volvocars.net:5045" }}
      action: debug:log
      input:
        message: 'selected Prod_ocpplatform.logstash-logs.volvocars.net:5045'

    - id: for test
      name: Create Contact Point test
      if: ${{ parameters.OCP_LOGSTASH_SERVER === "Test_ocpplatform.logstash-logs.volvocars.net:5045" }}
      action: debug:log
      input:
        message: 'selected Test_ocpplatform.logstash-logs.volvocars.net:5045'
      

