apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: backstage-systems
  title: Gitops filebeat
  description: This template will create filebeat in Backstage
  tags:
    - filebeat
spec:
  owner: filebeat
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Provide Needed Information
      required:
        - OCP_LOGSTASH_SERVER
        - OCP_CLUSTER_NAME
        - OCP_CLUSTER_URL
      properties:
        OCP_LOGSTASH_SERVER:
          title: OCP_LOGSTASH_SERVER
          type: string
          description: Select OCP_LOGSTASH_SERVER
          default: Dev_ocpplatform.logstash-logs.volvocars.net:5045
          enum:
            - Dev_ocpplatform.logstash-logs.volvocars.net:5045
            - Prod_ocpplatform.logstash-logs.volvocars.net:5045
            - Test_ocpplatform.logstash-logs.volvocars.net:5045
          enumNames:
            - 'Dev_ocpplatform.logstash-logs.volvocars.net:5045'
            - 'Prod_ocpplatform.logstash-logs.volvocars.net:5045'
            - 'Test_ocpplatform.logstash-logs.volvocars.net:5045'
          
        OCP_CLUSTER_NAME:
          title: OCP_CLUSTER_NAME
          type: string
          description: Select OCP_CLUSTER_NAME
          default: sandbox-net
          enum:
            - sandbox-net
            - rnd-net
            - test-net
          enumNames:
            - 'sandbox-net'
            - 'rnd-net'
            - 'test-net'
          
        OCP_CLUSTER_URL:
          title: OCP_CLUSTER_URL
          type: string
          description: Enter your OCP_CLUSTER_URL
 
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'OCP_LOGSTASH_SERVER :, ${{ parameters.OCP_LOGSTASH_SERVER }}!'

    - id: trigger-workflow
      name: trigger workflow
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=demo&owner=venkatram8500'
        workflowId: branch.yml
        branchOrTagName: main
        workflowInputs:
          branch: 'new-branch'
        token: ${{ secrets.ACCESS }}
        
          
        
         
