apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: backstage-systems
  title: Gitops filebeat
  description: This template will create filebeat in Backstage
  tags:
    - filebeat

spec:
  owner: group:venkatram
  type: service
  parameters:
    - title: Provide Needed Information
      required:
        - OCP_LOGSTASH_SERVER

      properties:
        OCP_LOGSTASH_SERVER:
          title: OCP_LOGSTASH_SERVER
          type: string
          description: Select OCP_LOGSTASH_SERVER
          default: none
          enum:
            - Dev_ocpplatform.logstash-logs.volvocars.net:5045
            - Prod_ocpplatform.logstash-logs.volvocars.net:5045
            - Test_ocpplatform.logstash-logs.volvocars.net:5045

        AccessToken:
          title: Github Access Token
          type: string
          description: Provide the Github Access Token

      
      dependencies:
        OCP_LOGSTASH_SERVER:
          oneOf:
            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Dev_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME1:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: sandbox-net
                OCP_CLUSTER_URL1:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: sandbox.volvocars.net

            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Prod_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME2:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: prod-net
                OCP_CLUSTER_URL2:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: prod.volvocars.net


            - properties:
                OCP_LOGSTASH_SERVER:
                  const: Test_ocpplatform.logstash-logs.volvocars.net:5045
                OCP_CLUSTER_NAME3:
                  title: OCP_CLUSTER_NAME
                  type: string
                  description: Select OCP_CLUSTER_NAME
                  default: rnd-net
                OCP_CLUSTER_URL3:
                  title: OCP_CLUSTER_URL
                  type: string
                  description: Enter your OCP_CLUSTER_URL
                  default: rnd.volvocars.net
                  



  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'OCP_LOGSTASH_SERVER :, ${{ parameters.OCP_LOGSTASH_SERVER }}!'

    - id: trigger-workflow
      name: trigger workflow
      action: github:actions:dispatch
      input:
        repoUrl: 'github.com?repo=demo&owner=venkatram8500'
        workflowId: branch.yml
        branchOrTagName: main
        workflowInputs:
          branch: 'new-branch'
        token: ${{ parameters.AccessToken }}
      

