name: Create branch

on:
  workflow_dispatch:

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    

      - name: Create new branch
        run: git checkout -b new-branch

      - name: Push new branch
        run: git push --set-upstream origin new-branch
