name: Create Branch Manually

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and push branch
      run: |
        # Replace BRANCH_NAME with the desired branch name
        BRANCH_NAME="your-branch-name"


        git clone https://venkatram8500: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@github.com/venkatram8500/demo.git

        cd demo

        echo "changing to demo"
     

