name: Create Branch Manually

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and push branch
      run: |
        # Replace BRANCH_NAME with the desired branch name
        git clone https://venkatram8500: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@github.com/venkatram8500/demo.git

    - name: display files
      run: ls

    - name: enter demo directory
      run: cd demo

    - name: create branch 
      run: git checkout -b try

    - name: show branches
      run: git branch

    - name: add and commit changes
      run: |
          cd demo
          ls
          git config --global user.name "venkatram8500"
          git config --global user.email "VMADHIRI@volvocars.com"
          
          

   

     

