name: Create Branch Manually

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS }}
      with:
        branch: 'release-notes'
        
    

          
          

   

     

