name: Create branch and run action manually

on:
  workflow_dispatch:

jobs:
  create-branch-and-run-action:
    runs-on: ubuntu-latest

    steps:
      - name: Create branch
        run: |
          git checkout -b new-branch
          git push -u origin new-branch

      - name: Run action
        run: |
          # Replace this step with the action you want to run.
          echo "Hello, world!"
