name: Update File
on:
    workflow_dispatch: 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS }}
          path: configmap.yml
          content: 'Updated by update-file action'
