name: Create branch and run action manually

on:
  workflow_dispatch:

jobs:
  create-branch-and-run-action:
    runs-on: ubuntu-latest

    steps:
   
    - uses: rmeneely/update-yaml@v1
      with:
        infile: configmap.yaml
        varlist: 'kind=try'
