name: Create branch and run action manually

on:
  workflow_dispatch:

jobs:
  create-branch-and-run-action:
    runs-on: ubuntu-latest

    steps:
        - name: Modify test test/overwrite.file.md
          uses: jaywcjlove/github-action-modify-file-content@main
          with:
            branch: new-branch
            path: new-branch/README.md
            body: "{{date:YYYY-MM-DD HH:mm:ss}}"
            overwrite: 'true'
            token: ${{ secrets.ACCESS }}
        
