name: Update File
on:
    workflow_dispatch: 
        inputs:
          clustername:
            description: "cluster name"
            required: true
            type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/update-file@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS }}
          path: configmap.yml
          content: |
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: ocp-sandbox-net-cm
                  namespace: flux-system
                data:
                  FILEBEAT_NAMESPACE: ocp-logging        
                  OCP_LOGSTASH_SERVER: ocpplatform.logstash-logs.volvocars.net:5045
                  OCP_CLUSTER_NAME: '${{ inputs.clustername }}'
                  OCP_CLUSTER_URL: "https://console-openshift-console.apps.sandbox-net.sandbox.volvocars.net"
